version: "3.9"
   
services:
  valheim:
    image: bonebroke/valheim-server:latest
    env_file: env.conf
    ports:
      - "2456-2458:2456-2458"
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
      - ./save:/home/steam/save
    tty: true
    stdin_open: true